# SPDX-FileCopyrightText: NONE
#
# SPDX-License-Identifier: CC0-1.0

name: General tests

on:
  push:

env:
  CARGO_TERM_COLOR: always
  CARGO_PROFILE_TEST_DEBUG: 0 # See https://corrode.dev/blog/tips-for-faster-ci-builds/

defaults:
  run:
    working-directory: ./daemon

jobs:
  build_and_test:
    name: Run tests
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust toolchain
        run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            daemon
            daemon/integration-tests
          cache-on-failure: true
      - name: Build Teamtype
        run: cargo build --release
      - name: Add teamtype binary to PATH
        run: echo "$PWD/target/release" >> $GITHUB_PATH
      - run: teamtype --version
      - name: Compile unit tests
        run: cargo test --no-default-features --no-run --locked
      - name: Run unit tests
        run: cargo test --no-default-features
      - name: Compile integration tests
        working-directory: ./daemon/integration-tests
        run: cargo test --no-run --locked
      - name: Build check
        working-directory: ./daemon/integration-tests
        run: cargo check --all-features
